CREATE TABLE PRODUCT_TBL (
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT VARCHAR(255) NOT NULL,
    UNIT VARCHAR(255) NOT NULL,
    COST DECIMAL(20,2),
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE DISCOUNT_TBL (
    DISCOUNT_ID INT NOT NULL AUTO_INCREMENT,
    OFFER VARCHAR(255) NOT NULL,
    VALID_FROM DATE NOT NULL,
    VALID_TO DATE NOT NULL,
    PRIMARY KEY (DISCOUNT_ID)
);

INSERT INTO PRODUCT_TBL(PRODUCT, UNIT, COST) VALUES ('SOUP', 'TIN', 0.65);
INSERT INTO PRODUCT_TBL(PRODUCT, UNIT, COST) VALUES ('BREAD', 'LOAF', 0.80);
INSERT INTO PRODUCT_TBL(PRODUCT, UNIT, COST) VALUES ('MILK', 'BOTTLE', 1.30);
INSERT INTO PRODUCT_TBL(PRODUCT, UNIT, COST) VALUES ('APPLES', 'SINGLE', 0.10);

INSERT INTO DISCOUNT_TBL(OFFER, VALID_FROM, VALID_TO) VALUES('Buy 2 tins of soup and get a loaf of bread half price', DATEADD(DAY, -1, NOW()), DATEADD(DAY, 7, NOW()));
INSERT INTO DISCOUNT_TBL(OFFER, VALID_FROM, VALID_TO) VALUES('Apples have a 10% discount', DATEADD(DAY, 3, NOW()), DATEADD(dd, -DAY(DATEADD(m,1,NOW())), DATEADD(m,1,NOW())));

SELECT * FROM DISCOUNT_TBL;