CREATE TABLE PRODUCT_TBL (
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT VARCHAR(255) NOT NULL,
    UNIT VARCHAR(255) NOT NULL,
    COST DECIMAL(20,2),
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE DISCOUNT_TBL (
    DISCOUNT_ID INT NOT NULL AUTO_INCREMENT,
    OFFER VARCHAR(255) NOT NULL,
    VALID_FROM DATE NOT NULL,
    VALID_TO DATE NOT NULL,
    PRIMARY KEY (DISCOUNT_ID)
);

CREATE TABLE DISCOUNT_PRODUCT_TBL (
    DISC_PROD_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID INT NOT NULL,
    DISCOUNT_ID INT NOT NULL,
    PRIMARY KEY (DISC_PROD_ID),
    CONSTRAINT "PRODUCT_FK" FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_TBL (PRODUCT_ID),
    CONSTRAINT "DISCOUNT_FK" FOREIGN KEY (DISCOUNT_ID) REFERENCES DISCOUNT_TBL (DISCOUNT_ID)
);

INSERT INTO PRODUCT_TBL(PRODUCT, UNIT, COST) VALUES ('SOUP', 'TIN', 0.65);
INSERT INTO PRODUCT_TBL(PRODUCT, UNIT, COST) VALUES ('BREAD', 'LOAF', 0.80);
INSERT INTO PRODUCT_TBL(PRODUCT, UNIT, COST) VALUES ('MILK', 'BOTTLE', 1.30);
INSERT INTO PRODUCT_TBL(PRODUCT, UNIT, COST) VALUES ('APPLE', 'SINGLE', 0.10);

INSERT INTO DISCOUNT_TBL(OFFER, VALID_FROM, VALID_TO) VALUES('Buy 2 tins of soup and get a loaf of bread half price', DATEADD(DAY, -1, NOW()), DATEADD(DAY, 7, NOW()));
INSERT INTO DISCOUNT_TBL(OFFER, VALID_FROM, VALID_TO) VALUES('Apples have a 10% discount', DATEADD(DAY, 3, NOW()), DATEADD(DAY, -DAY(DATEADD(MONTH,1,NOW())), DATEADD(MONTH,2,NOW())));

INSERT INTO DISCOUNT_PRODUCT_TBL(DISCOUNT_ID, PRODUCT_ID) VALUES(1,1);
INSERT INTO DISCOUNT_PRODUCT_TBL(DISCOUNT_ID, PRODUCT_ID) VALUES(1,2);
INSERT INTO DISCOUNT_PRODUCT_TBL(DISCOUNT_ID, PRODUCT_ID) VALUES(2,4);





SELECT * FROM DISCOUNT_TBL;